version: '2'
services:
    meuspedidos-app:
        image: meuspedidos
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://meuspedidos-mysql:3306/meuspedidos?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    meuspedidos-mysql:
        extends:
            file: mysql.yml
            service: meuspedidos-mysql
